### PR TITLE
loose the breach/cooldown duration in policy validator

### PR DESCRIPTION
**Pull request by cdlliuy**
I just loose the min_value of breach and cooldown duration to 1 directly in this PR

### CODE REVIEW

**Comment by silvestre** [comment]
Would it maybe make sense to couple the minimum cooldown to `evaluation_manager_execute_interval` in the eventgenerator config? Because if not, I think it will be possible to set cooldowns lower than the interval in which rules will be evaluated, which could be confusing for users, and look like a bug to them.

**Comment by boyang9527** [comment]
I am with Silvestre.   We can make them lower but they should not be lower than the aggregate interval.  If we allow cooldown to be very low, it will also cause issue when you are scale out autoscaler components.

**Comment by cdlliuy** [comment]
@boyang9527  @silvestre  ,then we need to align the min value with `collect_interval`, `aggregator_execute_interval` and `evaluation_manager_execute_interval` ...  
If these 3 parameters  are different, then we need to choose the max of these three as the minimum breach_duration /cooldown setting ..    
And also, this limitation would change per deployment ...  The policy which works for deployment A will be invalid for deployment B ...    I think this is not good to setup API / policy specification ..

**Comment by cdlliuy** [comment]
@boyang9527  @silvestre  @qibobo , please review the PR again.  
I changed the min breach/cooldown setting to be configurable in Node.js API server now.  
For Go API server,   the schema.json would be configurable in its bosh release job, so no need for further source code update.

**Comment by silvestre** [comment]
LGTM

**Pull request merged**
