### PR TITLE
skip creating appinstancemetrics table if it exists for migrating from metricscollector to metricsserver

### PR DESCRIPTION
**Pull request by qibobo**

### CODE REVIEW

**Comment by paltanmoy** [comment]
@qibobo  please double check these scenarios : 
1. New deployment with metricscollector 2. New deployment with metricsserver/metricsgateway 3. Migrate from metricscollector to metricsserver/metricsgateway 4. Revert back from metricsserver/metricsgateway to metricscollector 

Any of these 4 scenarios should not break.

**Comment by qibobo** [comment]
@paltanmoy Finished the tests. Below are the steps:
1 New deployment with metricscollector
2 Migrate from metricscollector to metricsserver/metricsgateway
3 Revert back from metricsserver/metricsgateway to metricscollector
4 Delete app-autoscaler deployment
5 New deployment with metricsserver/metricsgateway

**Comment by paltanmoy** [comment]
@qibobo 👍

**Comment by cdlliuy** [comment]
LGTM

**Comment by paltanmoy** [comment]
LGTM

**Pull request merged**
