### PR TITLE
Allow uaa clients interact with autoscaler api

### PR DESCRIPTION
**Pull request by daviddob**
This changes the auth flow to check if a token has the admin scope before checking space developer access. This cuts down on the number of requests to uaa as well as allows clients with cloud_controller.admin to use the autoscaler api where currently clients (even those with admin scope) will fail to auth based on the fact they cant be space developers as well as do not have openid scope for UAA.

If a client connects without admin scope the behavior remains the same as currently implemented with the response being "Failed to check space developer permission". This may not be ideal, however it quickly enables the functionality required while not introducing breaking changes.

### CODE REVIEW

**Comment by aqan213** [comment]
@daviddob the travis test was failed. can you please fix it? thanks,

**Review by silvestre — CHANGES_REQUESTED** [review]
I don't think it is a good idea to first check for admin permissions - generally I would expect there to be way more space developers than admins so the check for space developer permission should be the first with the admin check as a fallback.

To be honest I could not reproduce the error with an admin user - I could access the App Autoscaler API without issues.

What was the exact error? Maybe we can start from there.

**Comment by daviddob** [comment]
The issue with checking space developer first is that client_ids for service accounts do not have the openID scopes and the current check results in a 500 currently as they are not full users. A client with cloud_controller.admin should be able to use the autoscaler-api and not need to be a full user with space developer permissions. This is currently not possible.

**Comment by lnguyen** [comment]
If the tests were fixed, can this be merged in? are there app autoscaler maintainers? @silvestre ?

**Comment by silvestre** [comment]
Yes, sure! We are currently working on switching the tests over to Github Actions (#584), as travis-ci.org is sunsetting, but when the tests are green we can get to merging this.

**Comment by lnguyen** [comment]
@silvestre can we get approved to run tests?

**Review by lnguyen — APPROVED** [review]
Can this be approved? Per Dave comments?

**Comment by silvestre** [comment]
@lnguyen @daviddob Thank your for your contribution! 

It's very much appreciated. 

We should be quicker from now on to get such requests merged. :smiley:

**Review by silvestre — APPROVED** [review]

**Pull request merged**
